/**
 * DBA 2020
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AllDeviceDTO;
import io.swagger.client.model.AllMachineDTO;
import io.swagger.client.model.MachineDataRecordsDTO;
import io.swagger.client.model.GetRecordsForMachineDTO;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReaddatacontrollerApi
 */
public class ReaddatacontrollerApiTest {

    private final ReaddatacontrollerApi api = new ReaddatacontrollerApi();

    
    /**
     * getAllDevice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllDeviceUsingPOSTTest() throws ApiException {
        // AllDeviceDTO response = api.getAllDeviceUsingPOST();

        // TODO: test validations
    }
    
    /**
     * getAllMachines
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllMachinesUsingPOSTTest() throws ApiException {
        // AllMachineDTO response = api.getAllMachinesUsingPOST();

        // TODO: test validations
    }
    
    /**
     * getRecordsForMachine
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecordsForMachineUsingPOSTTest() throws ApiException {
        GetRecordsForMachineDTO getRecordsForMachineDTO = null;
        // MachineDataRecordsDTO response = api.getRecordsForMachineUsingPOST(getRecordsForMachineDTO);

        // TODO: test validations
    }
    
}
