/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EntityModelMachineEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntityModelMachineEntityTests
    {
        // TODO uncomment below to declare an instance variable for EntityModelMachineEntity
        //private EntityModelMachineEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntityModelMachineEntity
            //instance = new EntityModelMachineEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntityModelMachineEntity
        /// </summary>
        [Test]
        public void EntityModelMachineEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntityModelMachineEntity
            //Assert.IsInstanceOfType<EntityModelMachineEntity> (instance, "variable 'instance' is a EntityModelMachineEntity");
        }

        /// <summary>
        /// Test the property 'DeviceEntity'
        /// </summary>
        [Test]
        public void DeviceEntityTest()
        {
            // TODO unit test for the property 'DeviceEntity'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'MachineEntityState'
        /// </summary>
        [Test]
        public void MachineEntityStateTest()
        {
            // TODO unit test for the property 'MachineEntityState'
        }
        /// <summary>
        /// Test the property 'Vin'
        /// </summary>
        [Test]
        public void VinTest()
        {
            // TODO unit test for the property 'Vin'
        }

    }

}
