/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MachineDataRecordDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MachineDataRecordDTOTests
    {
        // TODO uncomment below to declare an instance variable for MachineDataRecordDTO
        //private MachineDataRecordDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MachineDataRecordDTO
            //instance = new MachineDataRecordDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MachineDataRecordDTO
        /// </summary>
        [Test]
        public void MachineDataRecordDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MachineDataRecordDTO
            //Assert.IsInstanceOfType<MachineDataRecordDTO> (instance, "variable 'instance' is a MachineDataRecordDTO");
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'DeviceConfigurationDTO'
        /// </summary>
        [Test]
        public void DeviceConfigurationDTOTest()
        {
            // TODO unit test for the property 'DeviceConfigurationDTO'
        }
        /// <summary>
        /// Test the property 'GpsX'
        /// </summary>
        [Test]
        public void GpsXTest()
        {
            // TODO unit test for the property 'GpsX'
        }
        /// <summary>
        /// Test the property 'GpsY'
        /// </summary>
        [Test]
        public void GpsYTest()
        {
            // TODO unit test for the property 'GpsY'
        }
        /// <summary>
        /// Test the property 'Humidity'
        /// </summary>
        [Test]
        public void HumidityTest()
        {
            // TODO unit test for the property 'Humidity'
        }
        /// <summary>
        /// Test the property 'RestOfFuel'
        /// </summary>
        [Test]
        public void RestOfFuelTest()
        {
            // TODO unit test for the property 'RestOfFuel'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'SpeedX'
        /// </summary>
        [Test]
        public void SpeedXTest()
        {
            // TODO unit test for the property 'SpeedX'
        }
        /// <summary>
        /// Test the property 'SpeedY'
        /// </summary>
        [Test]
        public void SpeedYTest()
        {
            // TODO unit test for the property 'SpeedY'
        }
        /// <summary>
        /// Test the property 'SpeedZ'
        /// </summary>
        [Test]
        public void SpeedZTest()
        {
            // TODO unit test for the property 'SpeedZ'
        }
        /// <summary>
        /// Test the property 'StreesBattery'
        /// </summary>
        [Test]
        public void StreesBatteryTest()
        {
            // TODO unit test for the property 'StreesBattery'
        }
        /// <summary>
        /// Test the property 'Tensometer'
        /// </summary>
        [Test]
        public void TensometerTest()
        {
            // TODO unit test for the property 'Tensometer'
        }
        /// <summary>
        /// Test the property 'Vin'
        /// </summary>
        [Test]
        public void VinTest()
        {
            // TODO unit test for the property 'Vin'
        }

    }

}
