/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelAndView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelAndViewTests
    {
        // TODO uncomment below to declare an instance variable for ModelAndView
        //private ModelAndView instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelAndView
            //instance = new ModelAndView();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelAndView
        /// </summary>
        [Test]
        public void ModelAndViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelAndView
            //Assert.IsInstanceOfType<ModelAndView> (instance, "variable 'instance' is a ModelAndView");
        }

        /// <summary>
        /// Test the property 'Empty'
        /// </summary>
        [Test]
        public void EmptyTest()
        {
            // TODO unit test for the property 'Empty'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'ModelMap'
        /// </summary>
        [Test]
        public void ModelMapTest()
        {
            // TODO unit test for the property 'ModelMap'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Test]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }
        /// <summary>
        /// Test the property 'ViewName'
        /// </summary>
        [Test]
        public void ViewNameTest()
        {
            // TODO unit test for the property 'ViewName'
        }

    }

}
