/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BasicerrorcontrollerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BasicerrorcontrollerApiTests
    {
        private BasicerrorcontrollerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BasicerrorcontrollerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BasicerrorcontrollerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BasicerrorcontrollerApi
            //Assert.IsInstanceOfType(typeof(BasicerrorcontrollerApi), instance, "instance is a BasicerrorcontrollerApi");
        }

        
        /// <summary>
        /// Test ErrorHtmlUsingDELETE
        /// </summary>
        [Test]
        public void ErrorHtmlUsingDELETETest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingDELETE();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
        /// <summary>
        /// Test ErrorHtmlUsingGET
        /// </summary>
        [Test]
        public void ErrorHtmlUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingGET();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
        /// <summary>
        /// Test ErrorHtmlUsingHEAD
        /// </summary>
        [Test]
        public void ErrorHtmlUsingHEADTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingHEAD();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
        /// <summary>
        /// Test ErrorHtmlUsingOPTIONS
        /// </summary>
        [Test]
        public void ErrorHtmlUsingOPTIONSTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingOPTIONS();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
        /// <summary>
        /// Test ErrorHtmlUsingPATCH
        /// </summary>
        [Test]
        public void ErrorHtmlUsingPATCHTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingPATCH();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
        /// <summary>
        /// Test ErrorHtmlUsingPOST
        /// </summary>
        [Test]
        public void ErrorHtmlUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingPOST();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
        /// <summary>
        /// Test ErrorHtmlUsingPUT
        /// </summary>
        [Test]
        public void ErrorHtmlUsingPUTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorHtmlUsingPUT();
            //Assert.IsInstanceOf<ModelAndView> (response, "response is ModelAndView");
        }
        
    }

}
