/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BasicerrorcontrollerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BasicerrorcontrollerApiTests
    {
        private BasicerrorcontrollerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BasicerrorcontrollerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BasicerrorcontrollerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BasicerrorcontrollerApi
            //Assert.IsInstanceOfType(typeof(BasicerrorcontrollerApi), instance, "instance is a BasicerrorcontrollerApi");
        }

        
        /// <summary>
        /// Test ErrorUsingDELETE
        /// </summary>
        [Test]
        public void ErrorUsingDELETETest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingDELETE();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
        /// <summary>
        /// Test ErrorUsingGET
        /// </summary>
        [Test]
        public void ErrorUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingGET();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
        /// <summary>
        /// Test ErrorUsingHEAD
        /// </summary>
        [Test]
        public void ErrorUsingHEADTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingHEAD();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
        /// <summary>
        /// Test ErrorUsingOPTIONS
        /// </summary>
        [Test]
        public void ErrorUsingOPTIONSTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingOPTIONS();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
        /// <summary>
        /// Test ErrorUsingPATCH
        /// </summary>
        [Test]
        public void ErrorUsingPATCHTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingPATCH();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
        /// <summary>
        /// Test ErrorUsingPOST
        /// </summary>
        [Test]
        public void ErrorUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingPOST();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
        /// <summary>
        /// Test ErrorUsingPUT
        /// </summary>
        [Test]
        public void ErrorUsingPUTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ErrorUsingPUT();
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
        
    }

}
