/**
 * DBA 2020
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DeviceConfigurationEntity;
import io.swagger.client.model.MachineEntity;
import org.joda.time.DateTime;


/**
 * DeviceEntity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-08T21:24:51.847+02:00")
public class DeviceEntity   {
  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("deviceConfigurationEntity")
  private DeviceConfigurationEntity deviceConfigurationEntity = null;

  @SerializedName("deviceDescription")
  private String deviceDescription = null;

  /**
   * Gets or Sets deviceStateEntity
   */
  public enum DeviceStateEntityEnum {
    @SerializedName("STOP")
    STOP("STOP"),
    
    @SerializedName("RUNNING")
    RUNNING("RUNNING"),
    
    @SerializedName("WAITING")
    WAITING("WAITING");

    private String value;

    DeviceStateEntityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("deviceStateEntity")
  private DeviceStateEntityEnum deviceStateEntity = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("machineEntity")
  private MachineEntity machineEntity = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  public DeviceEntity created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public DeviceEntity deviceConfigurationEntity(DeviceConfigurationEntity deviceConfigurationEntity) {
    this.deviceConfigurationEntity = deviceConfigurationEntity;
    return this;
  }

   /**
   * Get deviceConfigurationEntity
   * @return deviceConfigurationEntity
  **/
  @ApiModelProperty(example = "null", value = "")
  public DeviceConfigurationEntity getDeviceConfigurationEntity() {
    return deviceConfigurationEntity;
  }

  public void setDeviceConfigurationEntity(DeviceConfigurationEntity deviceConfigurationEntity) {
    this.deviceConfigurationEntity = deviceConfigurationEntity;
  }

  public DeviceEntity deviceDescription(String deviceDescription) {
    this.deviceDescription = deviceDescription;
    return this;
  }

   /**
   * Get deviceDescription
   * @return deviceDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeviceDescription() {
    return deviceDescription;
  }

  public void setDeviceDescription(String deviceDescription) {
    this.deviceDescription = deviceDescription;
  }

  public DeviceEntity deviceStateEntity(DeviceStateEntityEnum deviceStateEntity) {
    this.deviceStateEntity = deviceStateEntity;
    return this;
  }

   /**
   * Get deviceStateEntity
   * @return deviceStateEntity
  **/
  @ApiModelProperty(example = "null", value = "")
  public DeviceStateEntityEnum getDeviceStateEntity() {
    return deviceStateEntity;
  }

  public void setDeviceStateEntity(DeviceStateEntityEnum deviceStateEntity) {
    this.deviceStateEntity = deviceStateEntity;
  }

  public DeviceEntity id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DeviceEntity machineEntity(MachineEntity machineEntity) {
    this.machineEntity = machineEntity;
    return this;
  }

   /**
   * Get machineEntity
   * @return machineEntity
  **/
  @ApiModelProperty(example = "null", value = "")
  public MachineEntity getMachineEntity() {
    return machineEntity;
  }

  public void setMachineEntity(MachineEntity machineEntity) {
    this.machineEntity = machineEntity;
  }

  public DeviceEntity serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceEntity deviceEntity = (DeviceEntity) o;
    return Objects.equals(this.created, deviceEntity.created) &&
        Objects.equals(this.deviceConfigurationEntity, deviceEntity.deviceConfigurationEntity) &&
        Objects.equals(this.deviceDescription, deviceEntity.deviceDescription) &&
        Objects.equals(this.deviceStateEntity, deviceEntity.deviceStateEntity) &&
        Objects.equals(this.id, deviceEntity.id) &&
        Objects.equals(this.machineEntity, deviceEntity.machineEntity) &&
        Objects.equals(this.serialNumber, deviceEntity.serialNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, deviceConfigurationEntity, deviceDescription, deviceStateEntity, id, machineEntity, serialNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceEntity {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    deviceConfigurationEntity: ").append(toIndentedString(deviceConfigurationEntity)).append("\n");
    sb.append("    deviceDescription: ").append(toIndentedString(deviceDescription)).append("\n");
    sb.append("    deviceStateEntity: ").append(toIndentedString(deviceStateEntity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    machineEntity: ").append(toIndentedString(machineEntity)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

