/**
 * DBA 2020
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * DeviceDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-21T01:32:09.218+02:00")
public class DeviceDTO   {
  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("deviceDescription")
  private String deviceDescription = null;

  /**
   * Gets or Sets deviceStateEntity
   */
  public enum DeviceStateEntityEnum {
    @SerializedName("STOP")
    STOP("STOP"),
    
    @SerializedName("RUNNING")
    RUNNING("RUNNING"),
    
    @SerializedName("WAITING")
    WAITING("WAITING"),
    
    @SerializedName("DELETED")
    DELETED("DELETED"),
    
    @SerializedName("NEW")
    NEW("NEW");

    private String value;

    DeviceStateEntityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("deviceStateEntity")
  private DeviceStateEntityEnum deviceStateEntity = null;

  @SerializedName("online")
  private Boolean online = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  public DeviceDTO created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public DeviceDTO deviceDescription(String deviceDescription) {
    this.deviceDescription = deviceDescription;
    return this;
  }

   /**
   * Get deviceDescription
   * @return deviceDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeviceDescription() {
    return deviceDescription;
  }

  public void setDeviceDescription(String deviceDescription) {
    this.deviceDescription = deviceDescription;
  }

  public DeviceDTO deviceStateEntity(DeviceStateEntityEnum deviceStateEntity) {
    this.deviceStateEntity = deviceStateEntity;
    return this;
  }

   /**
   * Get deviceStateEntity
   * @return deviceStateEntity
  **/
  @ApiModelProperty(example = "null", value = "")
  public DeviceStateEntityEnum getDeviceStateEntity() {
    return deviceStateEntity;
  }

  public void setDeviceStateEntity(DeviceStateEntityEnum deviceStateEntity) {
    this.deviceStateEntity = deviceStateEntity;
  }

  public DeviceDTO online(Boolean online) {
    this.online = online;
    return this;
  }

   /**
   * Get online
   * @return online
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOnline() {
    return online;
  }

  public void setOnline(Boolean online) {
    this.online = online;
  }

  public DeviceDTO serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceDTO deviceDTO = (DeviceDTO) o;
    return Objects.equals(this.created, deviceDTO.created) &&
        Objects.equals(this.deviceDescription, deviceDTO.deviceDescription) &&
        Objects.equals(this.deviceStateEntity, deviceDTO.deviceStateEntity) &&
        Objects.equals(this.online, deviceDTO.online) &&
        Objects.equals(this.serialNumber, deviceDTO.serialNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, deviceDescription, deviceStateEntity, online, serialNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceDTO {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    deviceDescription: ").append(toIndentedString(deviceDescription)).append("\n");
    sb.append("    deviceStateEntity: ").append(toIndentedString(deviceStateEntity)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

