/**
 * DBA 2020
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MachineDataRecordDTO;
import java.util.ArrayList;
import java.util.List;


/**
 * MachineDataRecordsDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-24T12:36:55.353+02:00")
public class MachineDataRecordsDTO   {
  @SerializedName("machineDataRecordDTOS")
  private List<MachineDataRecordDTO> machineDataRecordDTOS = new ArrayList<MachineDataRecordDTO>();

  @SerializedName("online")
  private Boolean online = null;

  public MachineDataRecordsDTO machineDataRecordDTOS(List<MachineDataRecordDTO> machineDataRecordDTOS) {
    this.machineDataRecordDTOS = machineDataRecordDTOS;
    return this;
  }

  public MachineDataRecordsDTO addMachineDataRecordDTOSItem(MachineDataRecordDTO machineDataRecordDTOSItem) {
    this.machineDataRecordDTOS.add(machineDataRecordDTOSItem);
    return this;
  }

   /**
   * Get machineDataRecordDTOS
   * @return machineDataRecordDTOS
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<MachineDataRecordDTO> getMachineDataRecordDTOS() {
    return machineDataRecordDTOS;
  }

  public void setMachineDataRecordDTOS(List<MachineDataRecordDTO> machineDataRecordDTOS) {
    this.machineDataRecordDTOS = machineDataRecordDTOS;
  }

  public MachineDataRecordsDTO online(Boolean online) {
    this.online = online;
    return this;
  }

   /**
   * Get online
   * @return online
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOnline() {
    return online;
  }

  public void setOnline(Boolean online) {
    this.online = online;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineDataRecordsDTO machineDataRecordsDTO = (MachineDataRecordsDTO) o;
    return Objects.equals(this.machineDataRecordDTOS, machineDataRecordsDTO.machineDataRecordDTOS) &&
        Objects.equals(this.online, machineDataRecordsDTO.online);
  }

  @Override
  public int hashCode() {
    return Objects.hash(machineDataRecordDTOS, online);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineDataRecordsDTO {\n");
    
    sb.append("    machineDataRecordDTOS: ").append(toIndentedString(machineDataRecordDTOS)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

