/**
 * DBA 2020
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DeviceConfigurationDTO;


/**
 * MachineDataRecordDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-21T01:32:09.218+02:00")
public class MachineDataRecordDTO   {
  @SerializedName("action")
  private String action = null;

  @SerializedName("create")
  private String create = null;

  @SerializedName("deviceConfigurationDTO")
  private DeviceConfigurationDTO deviceConfigurationDTO = null;

  @SerializedName("gpsX")
  private Double gpsX = null;

  @SerializedName("gpsY")
  private Double gpsY = null;

  @SerializedName("humidity")
  private Double humidity = null;

  @SerializedName("restOfFuel")
  private Double restOfFuel = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  @SerializedName("speedX")
  private Double speedX = null;

  @SerializedName("speedY")
  private Double speedY = null;

  @SerializedName("speedZ")
  private Double speedZ = null;

  @SerializedName("streesBattery")
  private Double streesBattery = null;

  @SerializedName("tensometer")
  private Double tensometer = null;

  @SerializedName("vin")
  private String vin = null;

  public MachineDataRecordDTO action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public MachineDataRecordDTO create(String create) {
    this.create = create;
    return this;
  }

   /**
   * Get create
   * @return create
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreate() {
    return create;
  }

  public void setCreate(String create) {
    this.create = create;
  }

  public MachineDataRecordDTO deviceConfigurationDTO(DeviceConfigurationDTO deviceConfigurationDTO) {
    this.deviceConfigurationDTO = deviceConfigurationDTO;
    return this;
  }

   /**
   * Get deviceConfigurationDTO
   * @return deviceConfigurationDTO
  **/
  @ApiModelProperty(example = "null", value = "")
  public DeviceConfigurationDTO getDeviceConfigurationDTO() {
    return deviceConfigurationDTO;
  }

  public void setDeviceConfigurationDTO(DeviceConfigurationDTO deviceConfigurationDTO) {
    this.deviceConfigurationDTO = deviceConfigurationDTO;
  }

  public MachineDataRecordDTO gpsX(Double gpsX) {
    this.gpsX = gpsX;
    return this;
  }

   /**
   * Get gpsX
   * @return gpsX
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getGpsX() {
    return gpsX;
  }

  public void setGpsX(Double gpsX) {
    this.gpsX = gpsX;
  }

  public MachineDataRecordDTO gpsY(Double gpsY) {
    this.gpsY = gpsY;
    return this;
  }

   /**
   * Get gpsY
   * @return gpsY
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getGpsY() {
    return gpsY;
  }

  public void setGpsY(Double gpsY) {
    this.gpsY = gpsY;
  }

  public MachineDataRecordDTO humidity(Double humidity) {
    this.humidity = humidity;
    return this;
  }

   /**
   * Get humidity
   * @return humidity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getHumidity() {
    return humidity;
  }

  public void setHumidity(Double humidity) {
    this.humidity = humidity;
  }

  public MachineDataRecordDTO restOfFuel(Double restOfFuel) {
    this.restOfFuel = restOfFuel;
    return this;
  }

   /**
   * Get restOfFuel
   * @return restOfFuel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getRestOfFuel() {
    return restOfFuel;
  }

  public void setRestOfFuel(Double restOfFuel) {
    this.restOfFuel = restOfFuel;
  }

  public MachineDataRecordDTO serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public MachineDataRecordDTO speedX(Double speedX) {
    this.speedX = speedX;
    return this;
  }

   /**
   * Get speedX
   * @return speedX
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSpeedX() {
    return speedX;
  }

  public void setSpeedX(Double speedX) {
    this.speedX = speedX;
  }

  public MachineDataRecordDTO speedY(Double speedY) {
    this.speedY = speedY;
    return this;
  }

   /**
   * Get speedY
   * @return speedY
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSpeedY() {
    return speedY;
  }

  public void setSpeedY(Double speedY) {
    this.speedY = speedY;
  }

  public MachineDataRecordDTO speedZ(Double speedZ) {
    this.speedZ = speedZ;
    return this;
  }

   /**
   * Get speedZ
   * @return speedZ
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSpeedZ() {
    return speedZ;
  }

  public void setSpeedZ(Double speedZ) {
    this.speedZ = speedZ;
  }

  public MachineDataRecordDTO streesBattery(Double streesBattery) {
    this.streesBattery = streesBattery;
    return this;
  }

   /**
   * Get streesBattery
   * @return streesBattery
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getStreesBattery() {
    return streesBattery;
  }

  public void setStreesBattery(Double streesBattery) {
    this.streesBattery = streesBattery;
  }

  public MachineDataRecordDTO tensometer(Double tensometer) {
    this.tensometer = tensometer;
    return this;
  }

   /**
   * Get tensometer
   * @return tensometer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTensometer() {
    return tensometer;
  }

  public void setTensometer(Double tensometer) {
    this.tensometer = tensometer;
  }

  public MachineDataRecordDTO vin(String vin) {
    this.vin = vin;
    return this;
  }

   /**
   * Get vin
   * @return vin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVin() {
    return vin;
  }

  public void setVin(String vin) {
    this.vin = vin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineDataRecordDTO machineDataRecordDTO = (MachineDataRecordDTO) o;
    return Objects.equals(this.action, machineDataRecordDTO.action) &&
        Objects.equals(this.create, machineDataRecordDTO.create) &&
        Objects.equals(this.deviceConfigurationDTO, machineDataRecordDTO.deviceConfigurationDTO) &&
        Objects.equals(this.gpsX, machineDataRecordDTO.gpsX) &&
        Objects.equals(this.gpsY, machineDataRecordDTO.gpsY) &&
        Objects.equals(this.humidity, machineDataRecordDTO.humidity) &&
        Objects.equals(this.restOfFuel, machineDataRecordDTO.restOfFuel) &&
        Objects.equals(this.serialNumber, machineDataRecordDTO.serialNumber) &&
        Objects.equals(this.speedX, machineDataRecordDTO.speedX) &&
        Objects.equals(this.speedY, machineDataRecordDTO.speedY) &&
        Objects.equals(this.speedZ, machineDataRecordDTO.speedZ) &&
        Objects.equals(this.streesBattery, machineDataRecordDTO.streesBattery) &&
        Objects.equals(this.tensometer, machineDataRecordDTO.tensometer) &&
        Objects.equals(this.vin, machineDataRecordDTO.vin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, create, deviceConfigurationDTO, gpsX, gpsY, humidity, restOfFuel, serialNumber, speedX, speedY, speedZ, streesBattery, tensometer, vin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineDataRecordDTO {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    deviceConfigurationDTO: ").append(toIndentedString(deviceConfigurationDTO)).append("\n");
    sb.append("    gpsX: ").append(toIndentedString(gpsX)).append("\n");
    sb.append("    gpsY: ").append(toIndentedString(gpsY)).append("\n");
    sb.append("    humidity: ").append(toIndentedString(humidity)).append("\n");
    sb.append("    restOfFuel: ").append(toIndentedString(restOfFuel)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    speedX: ").append(toIndentedString(speedX)).append("\n");
    sb.append("    speedY: ").append(toIndentedString(speedY)).append("\n");
    sb.append("    speedZ: ").append(toIndentedString(speedZ)).append("\n");
    sb.append("    streesBattery: ").append(toIndentedString(streesBattery)).append("\n");
    sb.append("    tensometer: ").append(toIndentedString(tensometer)).append("\n");
    sb.append("    vin: ").append(toIndentedString(vin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

