/**
 * DBA 2020
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.View;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * ModelAndView
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-08T14:25:41.506+02:00")
public class ModelAndView   {
  @SerializedName("empty")
  private Boolean empty = null;

  @SerializedName("model")
  private Object model = null;

  @SerializedName("modelMap")
  private Map<String, Object> modelMap = new HashMap<String, Object>();

  @SerializedName("reference")
  private Boolean reference = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("CONTINUE")
    CONTINUE("CONTINUE"),
    
    @SerializedName("SWITCHING_PROTOCOLS")
    SWITCHING_PROTOCOLS("SWITCHING_PROTOCOLS"),
    
    @SerializedName("PROCESSING")
    PROCESSING("PROCESSING"),
    
    @SerializedName("CHECKPOINT")
    CHECKPOINT("CHECKPOINT"),
    
    @SerializedName("OK")
    OK("OK"),
    
    @SerializedName("CREATED")
    CREATED("CREATED"),
    
    @SerializedName("ACCEPTED")
    ACCEPTED("ACCEPTED"),
    
    @SerializedName("NON_AUTHORITATIVE_INFORMATION")
    NON_AUTHORITATIVE_INFORMATION("NON_AUTHORITATIVE_INFORMATION"),
    
    @SerializedName("NO_CONTENT")
    NO_CONTENT("NO_CONTENT"),
    
    @SerializedName("RESET_CONTENT")
    RESET_CONTENT("RESET_CONTENT"),
    
    @SerializedName("PARTIAL_CONTENT")
    PARTIAL_CONTENT("PARTIAL_CONTENT"),
    
    @SerializedName("MULTI_STATUS")
    MULTI_STATUS("MULTI_STATUS"),
    
    @SerializedName("ALREADY_REPORTED")
    ALREADY_REPORTED("ALREADY_REPORTED"),
    
    @SerializedName("IM_USED")
    IM_USED("IM_USED"),
    
    @SerializedName("MULTIPLE_CHOICES")
    MULTIPLE_CHOICES("MULTIPLE_CHOICES"),
    
    @SerializedName("MOVED_PERMANENTLY")
    MOVED_PERMANENTLY("MOVED_PERMANENTLY"),
    
    @SerializedName("FOUND")
    FOUND("FOUND"),
    
    @SerializedName("MOVED_TEMPORARILY")
    MOVED_TEMPORARILY("MOVED_TEMPORARILY"),
    
    @SerializedName("SEE_OTHER")
    SEE_OTHER("SEE_OTHER"),
    
    @SerializedName("NOT_MODIFIED")
    NOT_MODIFIED("NOT_MODIFIED"),
    
    @SerializedName("USE_PROXY")
    USE_PROXY("USE_PROXY"),
    
    @SerializedName("TEMPORARY_REDIRECT")
    TEMPORARY_REDIRECT("TEMPORARY_REDIRECT"),
    
    @SerializedName("PERMANENT_REDIRECT")
    PERMANENT_REDIRECT("PERMANENT_REDIRECT"),
    
    @SerializedName("BAD_REQUEST")
    BAD_REQUEST("BAD_REQUEST"),
    
    @SerializedName("UNAUTHORIZED")
    UNAUTHORIZED("UNAUTHORIZED"),
    
    @SerializedName("PAYMENT_REQUIRED")
    PAYMENT_REQUIRED("PAYMENT_REQUIRED"),
    
    @SerializedName("FORBIDDEN")
    FORBIDDEN("FORBIDDEN"),
    
    @SerializedName("NOT_FOUND")
    NOT_FOUND("NOT_FOUND"),
    
    @SerializedName("METHOD_NOT_ALLOWED")
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    
    @SerializedName("NOT_ACCEPTABLE")
    NOT_ACCEPTABLE("NOT_ACCEPTABLE"),
    
    @SerializedName("PROXY_AUTHENTICATION_REQUIRED")
    PROXY_AUTHENTICATION_REQUIRED("PROXY_AUTHENTICATION_REQUIRED"),
    
    @SerializedName("REQUEST_TIMEOUT")
    REQUEST_TIMEOUT("REQUEST_TIMEOUT"),
    
    @SerializedName("CONFLICT")
    CONFLICT("CONFLICT"),
    
    @SerializedName("GONE")
    GONE("GONE"),
    
    @SerializedName("LENGTH_REQUIRED")
    LENGTH_REQUIRED("LENGTH_REQUIRED"),
    
    @SerializedName("PRECONDITION_FAILED")
    PRECONDITION_FAILED("PRECONDITION_FAILED"),
    
    @SerializedName("PAYLOAD_TOO_LARGE")
    PAYLOAD_TOO_LARGE("PAYLOAD_TOO_LARGE"),
    
    @SerializedName("REQUEST_ENTITY_TOO_LARGE")
    REQUEST_ENTITY_TOO_LARGE("REQUEST_ENTITY_TOO_LARGE"),
    
    @SerializedName("URI_TOO_LONG")
    URI_TOO_LONG("URI_TOO_LONG"),
    
    @SerializedName("REQUEST_URI_TOO_LONG")
    REQUEST_URI_TOO_LONG("REQUEST_URI_TOO_LONG"),
    
    @SerializedName("UNSUPPORTED_MEDIA_TYPE")
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    
    @SerializedName("REQUESTED_RANGE_NOT_SATISFIABLE")
    REQUESTED_RANGE_NOT_SATISFIABLE("REQUESTED_RANGE_NOT_SATISFIABLE"),
    
    @SerializedName("EXPECTATION_FAILED")
    EXPECTATION_FAILED("EXPECTATION_FAILED"),
    
    @SerializedName("I_AM_A_TEAPOT")
    I_AM_A_TEAPOT("I_AM_A_TEAPOT"),
    
    @SerializedName("INSUFFICIENT_SPACE_ON_RESOURCE")
    INSUFFICIENT_SPACE_ON_RESOURCE("INSUFFICIENT_SPACE_ON_RESOURCE"),
    
    @SerializedName("METHOD_FAILURE")
    METHOD_FAILURE("METHOD_FAILURE"),
    
    @SerializedName("DESTINATION_LOCKED")
    DESTINATION_LOCKED("DESTINATION_LOCKED"),
    
    @SerializedName("UNPROCESSABLE_ENTITY")
    UNPROCESSABLE_ENTITY("UNPROCESSABLE_ENTITY"),
    
    @SerializedName("LOCKED")
    LOCKED("LOCKED"),
    
    @SerializedName("FAILED_DEPENDENCY")
    FAILED_DEPENDENCY("FAILED_DEPENDENCY"),
    
    @SerializedName("TOO_EARLY")
    TOO_EARLY("TOO_EARLY"),
    
    @SerializedName("UPGRADE_REQUIRED")
    UPGRADE_REQUIRED("UPGRADE_REQUIRED"),
    
    @SerializedName("PRECONDITION_REQUIRED")
    PRECONDITION_REQUIRED("PRECONDITION_REQUIRED"),
    
    @SerializedName("TOO_MANY_REQUESTS")
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),
    
    @SerializedName("REQUEST_HEADER_FIELDS_TOO_LARGE")
    REQUEST_HEADER_FIELDS_TOO_LARGE("REQUEST_HEADER_FIELDS_TOO_LARGE"),
    
    @SerializedName("UNAVAILABLE_FOR_LEGAL_REASONS")
    UNAVAILABLE_FOR_LEGAL_REASONS("UNAVAILABLE_FOR_LEGAL_REASONS"),
    
    @SerializedName("INTERNAL_SERVER_ERROR")
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    
    @SerializedName("NOT_IMPLEMENTED")
    NOT_IMPLEMENTED("NOT_IMPLEMENTED"),
    
    @SerializedName("BAD_GATEWAY")
    BAD_GATEWAY("BAD_GATEWAY"),
    
    @SerializedName("SERVICE_UNAVAILABLE")
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    
    @SerializedName("GATEWAY_TIMEOUT")
    GATEWAY_TIMEOUT("GATEWAY_TIMEOUT"),
    
    @SerializedName("HTTP_VERSION_NOT_SUPPORTED")
    HTTP_VERSION_NOT_SUPPORTED("HTTP_VERSION_NOT_SUPPORTED"),
    
    @SerializedName("VARIANT_ALSO_NEGOTIATES")
    VARIANT_ALSO_NEGOTIATES("VARIANT_ALSO_NEGOTIATES"),
    
    @SerializedName("INSUFFICIENT_STORAGE")
    INSUFFICIENT_STORAGE("INSUFFICIENT_STORAGE"),
    
    @SerializedName("LOOP_DETECTED")
    LOOP_DETECTED("LOOP_DETECTED"),
    
    @SerializedName("BANDWIDTH_LIMIT_EXCEEDED")
    BANDWIDTH_LIMIT_EXCEEDED("BANDWIDTH_LIMIT_EXCEEDED"),
    
    @SerializedName("NOT_EXTENDED")
    NOT_EXTENDED("NOT_EXTENDED"),
    
    @SerializedName("NETWORK_AUTHENTICATION_REQUIRED")
    NETWORK_AUTHENTICATION_REQUIRED("NETWORK_AUTHENTICATION_REQUIRED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("view")
  private View view = null;

  @SerializedName("viewName")
  private String viewName = null;

  public ModelAndView empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }

  public ModelAndView model(Object model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getModel() {
    return model;
  }

  public void setModel(Object model) {
    this.model = model;
  }

  public ModelAndView modelMap(Map<String, Object> modelMap) {
    this.modelMap = modelMap;
    return this;
  }

  public ModelAndView putModelMapItem(String key, Object modelMapItem) {
    this.modelMap.put(key, modelMapItem);
    return this;
  }

   /**
   * Get modelMap
   * @return modelMap
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Object> getModelMap() {
    return modelMap;
  }

  public void setModelMap(Map<String, Object> modelMap) {
    this.modelMap = modelMap;
  }

  public ModelAndView reference(Boolean reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getReference() {
    return reference;
  }

  public void setReference(Boolean reference) {
    this.reference = reference;
  }

  public ModelAndView status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ModelAndView view(View view) {
    this.view = view;
    return this;
  }

   /**
   * Get view
   * @return view
  **/
  @ApiModelProperty(example = "null", value = "")
  public View getView() {
    return view;
  }

  public void setView(View view) {
    this.view = view;
  }

  public ModelAndView viewName(String viewName) {
    this.viewName = viewName;
    return this;
  }

   /**
   * Get viewName
   * @return viewName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getViewName() {
    return viewName;
  }

  public void setViewName(String viewName) {
    this.viewName = viewName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelAndView modelAndView = (ModelAndView) o;
    return Objects.equals(this.empty, modelAndView.empty) &&
        Objects.equals(this.model, modelAndView.model) &&
        Objects.equals(this.modelMap, modelAndView.modelMap) &&
        Objects.equals(this.reference, modelAndView.reference) &&
        Objects.equals(this.status, modelAndView.status) &&
        Objects.equals(this.view, modelAndView.view) &&
        Objects.equals(this.viewName, modelAndView.viewName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(empty, model, modelMap, reference, status, view, viewName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelAndView {\n");
    
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    modelMap: ").append(toIndentedString(modelMap)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    viewName: ").append(toIndentedString(viewName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

