/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// MachineDataRecordsDTO
    /// </summary>
    [DataContract]
    public partial class MachineDataRecordsDTO :  IEquatable<MachineDataRecordsDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MachineDataRecordsDTO" /> class.
        /// </summary>
        /// <param name="MachineDataRecordDTOS">MachineDataRecordDTOS.</param>
        /// <param name="Online">Online.</param>
        public MachineDataRecordsDTO(List<MachineDataRecordDTO> MachineDataRecordDTOS = null, bool? Online = null)
        {
            this.MachineDataRecordDTOS = MachineDataRecordDTOS;
            this.Online = Online;
        }
        
        /// <summary>
        /// Gets or Sets MachineDataRecordDTOS
        /// </summary>
        [DataMember(Name="machineDataRecordDTOS", EmitDefaultValue=false)]
        public List<MachineDataRecordDTO> MachineDataRecordDTOS { get; set; }
        /// <summary>
        /// Gets or Sets Online
        /// </summary>
        [DataMember(Name="online", EmitDefaultValue=false)]
        public bool? Online { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MachineDataRecordsDTO {\n");
            sb.Append("  MachineDataRecordDTOS: ").Append(MachineDataRecordDTOS).Append("\n");
            sb.Append("  Online: ").Append(Online).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MachineDataRecordsDTO);
        }

        /// <summary>
        /// Returns true if MachineDataRecordsDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of MachineDataRecordsDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MachineDataRecordsDTO other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.MachineDataRecordDTOS == other.MachineDataRecordDTOS ||
                    this.MachineDataRecordDTOS != null &&
                    this.MachineDataRecordDTOS.SequenceEqual(other.MachineDataRecordDTOS)
                ) && 
                (
                    this.Online == other.Online ||
                    this.Online != null &&
                    this.Online.Equals(other.Online)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.MachineDataRecordDTOS != null)
                    hash = hash * 59 + this.MachineDataRecordDTOS.GetHashCode();
                if (this.Online != null)
                    hash = hash * 59 + this.Online.GetHashCode();
                return hash;
            }
        }
    }

}
