/* 
 * DBA 2020
 *
 * semestral work
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NewDeviceConfigurationDTO
    /// </summary>
    [DataContract]
    public partial class NewDeviceConfigurationDTO :  IEquatable<NewDeviceConfigurationDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewDeviceConfigurationDTO" /> class.
        /// </summary>
        /// <param name="Distance">Distance.</param>
        /// <param name="Latency">Latency.</param>
        /// <param name="Speed">Speed.</param>
        public NewDeviceConfigurationDTO(int? Distance = null, int? Latency = null, int? Speed = null)
        {
            this.Distance = Distance;
            this.Latency = Latency;
            this.Speed = Speed;
        }
        
        /// <summary>
        /// Gets or Sets Distance
        /// </summary>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public int? Distance { get; set; }
        /// <summary>
        /// Gets or Sets Latency
        /// </summary>
        [DataMember(Name="latency", EmitDefaultValue=false)]
        public int? Latency { get; set; }
        /// <summary>
        /// Gets or Sets Speed
        /// </summary>
        [DataMember(Name="speed", EmitDefaultValue=false)]
        public int? Speed { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NewDeviceConfigurationDTO {\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Latency: ").Append(Latency).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as NewDeviceConfigurationDTO);
        }

        /// <summary>
        /// Returns true if NewDeviceConfigurationDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of NewDeviceConfigurationDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NewDeviceConfigurationDTO other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Distance == other.Distance ||
                    this.Distance != null &&
                    this.Distance.Equals(other.Distance)
                ) && 
                (
                    this.Latency == other.Latency ||
                    this.Latency != null &&
                    this.Latency.Equals(other.Latency)
                ) && 
                (
                    this.Speed == other.Speed ||
                    this.Speed != null &&
                    this.Speed.Equals(other.Speed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Distance != null)
                    hash = hash * 59 + this.Distance.GetHashCode();
                if (this.Latency != null)
                    hash = hash * 59 + this.Latency.GetHashCode();
                if (this.Speed != null)
                    hash = hash * 59 + this.Speed.GetHashCode();
                return hash;
            }
        }
    }

}
